services:
  mongo:
    container_name: personal-portfolio-db
    image: mongo
    restart: always
    volumes:
      - personal-portfolio_db:/data/db
  server:
    container_name: personal-portfolio-server
    restart: always
    build:
      context: .
      args:
        REACT_HOST: ${HOST}
        CLOUD_NAME: ${CLOUD_NAME}
    env_file:
      - ./.env
    ports:
      - 2006:2002
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - mongo
volumes:
   personal-portfolio_db: